# sudo access is required
sudo: required
# Compilation language
language: d
# Use latest DMD
d: 
  - dmd

# What build architectures will we build on
env:
  - ARCH=x64
  - ARCH=x32
  - ARCH=arm32
  - ARCH=arm64
  - ARCH=ppc64le
  

script:
  - "bash -ex .travis-ci.sh"
